<a href="https://colab.research.google.com/github/skiaadi/Pandas/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment-8
#Numpy
##Aadi Havele
##25070123001

In [ ]:
import numpy as np

a=np.array([10,20,30,40])
b=np.array([[1,2,3],[4,5,6]])
print(a,b)

[10 20 30 40] [[1 2 3]
 [4 5 6]]


In [ ]:
a.ndim
b.ndim

2

In [ ]:
a.shape
b.shape

(2, 3)

In [ ]:
a.dtype
b.dtype


dtype('int64')

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.mean(a)

np.float64(25.0)

In [ ]:
np.median(a)

np.float64(25.0)

In [ ]:
np.min(a)

np.int64(10)

In [ ]:
np.sum(a)

np.int64(100)